version: '3'
services:

  # PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jsiebach/kirstensiebach
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    user: "1000:1000"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - storage:/var/www/storage
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./nginx/local/conf.d/:/etc/nginx/conf.d/
      - storage:/var/www/storage
    networks:
      - app-network

  # MySQL Service
  db:
    image: mysql:8.0.23
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: kirstensiebach
      MYSQL_DATABASE: kirstensiebach
      MYSQL_ROOT_PASSWORD: docker
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
  storage:
    driver: local
