on:
  pull_request:
    branches: [ dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Setup Nova Credentials
        run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Compile assets
        run: |
          npm install
          npm run production
      - name: Execute tests (Unit and Feature tests) via PHPUnit
        run: XDEBUG_MODE=coverage vendor/bin/phpunit --debug --coverage-clover ./coverage.xml
      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "80"
          filename: "coverage.xml"
          exit: false
      - name: Print test coverage
        run: echo "${{ steps.test-coverage.outputs.coverage }}"
