on:
  push:
    branches: [ dev ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl, pdo_mysql, zip, exif, pcntl, gd
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Compile assets
        run: |
          npm install
          npm run production
      - name: Setup Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Playwright dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Execute tests (Unit, Feature, and Browser tests) via Pest
        env:
          APP_URL: http://127.0.0.1:8000
        run: |
          php artisan serve > /dev/null 2>&1 &
          php artisan test

  merge-dev-to-master:
    runs-on: ubuntu-latest
    needs: laravel-tests
    steps:
      - uses: actions/checkout@master

      - name: Merge dev -> master
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: dev
          target_branch: master
          github_token: ${{ secrets.GIT_TOKEN }}
