on:
  push:
    branches: [ master ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl, pdo_mysql, zip, exif, pcntl, gd
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Compile assets
        run: |
          npm install
          npm run production
      - name: Setup Node.js for Playwright
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install Playwright dependencies
        run: |
          npm ci
          npx playwright install --with-deps
      - name: Execute tests (Unit, Feature, and Browser tests) via Pest
        env:
          APP_URL: http://127.0.0.1:8000
        run: |
          php artisan serve > /dev/null 2>&1 &
          XDEBUG_MODE=coverage php artisan test --coverage-clover ./coverage.xml
      - name: Upload Browser Screenshots on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: browser-screenshots
          path: tests/Browser/Screenshots
          if-no-files-found: ignore
      - name: Check test coverage
        id: test-coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        with:
          percentage: "80"
          filename: "coverage.xml"
          exit: false
      - name: Print test coverage
        run: echo "${{ steps.test-coverage.outputs.coverage }}"

  build-and-push-docker-image:
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          extensions: intl, pdo_mysql, zip, exif, pcntl, gd
      - name: Install Dependencies
        run: composer install --no-interaction
      - name: Compile assets
        run: |
          npm install
          npm run production
      - name: Directory Permissions
        run: chmod -R 775 storage bootstrap/cache
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push docker image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jsiebach/kirstensiebach:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Run deploy script via SSH
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ${{ secrets.SSH_DEPLOY_COMMAND }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
